name: Test Suite Template
on:
  pull_request:
    paths:
      - 'src/views/**'
      - 'src/Tribe/Views/**'
      - 'src/Events/SEO/**'
      - 'tests/views/${{ matrix.suite }}/**'
      - '.github/workflows/views-${{ matrix.suite }}.yml'
  push:
    branches: [ main, develop ]
    paths:
      - 'src/views/**'
      - 'src/Tribe/Views/**'
      - 'src/Events/SEO/**'
      - 'tests/views/${{ matrix.suite }}/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite: [core, components, partials, data, seo, integration, blocks, modules]
        php-version: [8.1, 8.2]
        wordpress-version: [latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, sqlite3, gd, exif, iconv
          coverage: none

      - name: Setup WordPress
        uses: wordpress/wordpress-testing-env@v1
        with:
          wordpress-version: ${{ matrix.wordpress-version }}

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress

      - name: Run ${{ matrix.suite }} tests
        run: |
          vendor/bin/codecept run views_${{ matrix.suite }} --env=ci
        env:
          WP_ROOT_FOLDER: /tmp/wordpress
          WP_TEST_DB_NAME: wordpress_test
          WP_TEST_DB_HOST: 127.0.0.1
          WP_TEST_DB_USER: root
          WP_TEST_DB_PASSWORD: root
          WP_DOMAIN: localhost
