<?php
// This class was automatically generated by build task
// You can change it manually, but it will be overwritten on next build

/**

 * Methods from PhpBrowser
 * @method WebGuy submitForm($selector, $params)
 * @method WebGuy sendAjaxPostRequest($uri)
 * @method WebGuy sendAjaxGetRequest($uri)
 * @method WebGuy amOnPage($page)
 * @method WebGuy dontSee($text)
 * @method WebGuy see($text)
 * @method WebGuy seeLink($text)
 * @method WebGuy dontSeeLink($text)
 * @method WebGuy click($link)
 * @method WebGuy reloadPage()
 * @method WebGuy moveBack()
 * @method WebGuy moveForward()
 * @method WebGuy fillField($field, $value)
 * @method WebGuy selectOption($select, $option)
 * @method WebGuy checkOption($option)
 * @method WebGuy uncheckOption($option)
 * @method WebGuy seeInCurrentUrl($uri)
 * @method WebGuy attachFile($field, $filename)
 * @method WebGuy seeCheckboxIsChecked($checkbox)
 * @method WebGuy dontSeeCheckboxIsChecked($checkbox)
 * @method WebGuy seeInField($field, $value)
 * @method WebGuy dontSeeInField($field, $value)
 * 
 * Methods from WebHelper
**/


class WebGuy extends \Codeception\AbstractGuy
{


}

