<?php
/**
 * Compact, accessible identity indicators for the native events list.
 *
 * @since TBD
 * @package TEC\Events\Recurrence\Admin
 */

declare( strict_types=1 );

namespace TEC\Events\Recurrence\Admin;

/** Read-only row identity renderer. @since TBD */
class Row_Identity {
	/**
	 * WordPress @wordpress/icons SVG paths: calendar, copy, repeat, map-marker.
	 * Source: https://github.com/WordPress/gutenberg/tree/trunk/packages/icons/src/library
	 *
	 * @since TBD
	 * @var array<string,string>
	 */
	private const ICONS = [
		'calendar'   => '<path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm.5 16c0 .3-.2.5-.5.5H5c-.3 0-.5-.2-.5-.5V7h15v12zM9 10H7v2h2v-2zm0 4H7v2h2v-2zm4-4h-2v2h2v-2zm4 0h-2v2h2v-2zm-4 4h-2v2h2v-2zm4 0h-2v2h2v-2z" />',
		'copy'       => '<path fill-rule="evenodd" clip-rule="evenodd" d="M5 4.5h11a.5.5 0 0 1 .5.5v11a.5.5 0 0 1-.5.5H5a.5.5 0 0 1-.5-.5V5a.5.5 0 0 1 .5-.5ZM3 5a2 2 0 0 1 2-2h11a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5Zm17 3v10.75c0 .69-.56 1.25-1.25 1.25H6v1.5h12.75a2.75 2.75 0 0 0 2.75-2.75V8H20Z" />',
		'repeat'     => '<path d="m14.47 11.47 1.06 1.061 1.72-1.72v4.439a.25.25 0 0 1-.25.25h-6.379l-1.5 1.5H17a1.75 1.75 0 0 0 1.75-1.75v-4.438l1.72 1.72 1.06-1.061L18 7.94zM7 7a1.75 1.75 0 0 0-1.75 1.75v4.44l-1.72-1.72-1.06 1.06L6 16.06l3.53-3.53-1.06-1.06-1.72 1.72V8.75A.25.25 0 0 1 7 8.5h6.379l1.5-1.5z" />',
		'map-marker' => '<path d="M12 9c-.8 0-1.5.7-1.5 1.5S11.2 12 12 12s1.5-.7 1.5-1.5S12.8 9 12 9zm0-5c-3.6 0-6.5 2.8-6.5 6.2 0 .8.3 1.8.9 3.1.5 1.1 1.2 2.3 2 3.6.7 1 3 3.8 3.2 3.9l.4.5.4-.5c.2-.2 2.6-2.9 3.2-3.9.8-1.2 1.5-2.5 2-3.6.6-1.3.9-2.3.9-3.1C18.5 6.8 15.6 4 12 4zm4.3 8.7c-.5 1-1.1 2.2-1.9 3.4-.5.7-1.7 2.2-2.4 3-.7-.8-1.9-2.3-2.4-3-.8-1.2-1.4-2.3-1.9-3.3-.6-1.4-.7-2.2-.7-2.5 0-2.6 2.2-4.7 5-4.7s5 2.1 5 4.7c0 .2-.1 1-.7 2.4z" />',
	];

	/**
	 * Renders the single identity icon in the native Type column, including without scripts.
	 *
	 * @since TBD
	 * @param array $data Shared presentation state.
	 * @param array $status Current Pro availability, used only by the lock.
	 * @return void
	 */
	public function render( array $data, array $status ): void {
		$id                     = wp_unique_id( 'tec-row-identity-' . $data['postId'] . '-' );
		$schedules              = [
			'single' => [ 'calendar', __( 'Single event · One scheduled date', 'the-events-calendar' ) ],
			'dates'  => [ 'copy', __( 'Multiple dates · Manually scheduled dates', 'the-events-calendar' ) ],
			'rules'  => [ 'repeat', __( 'Recurring event · Dates generated by recurrence rules', 'the-events-calendar' ) ],
		];
		[ $icon, $description ] = $schedules[ $data['schedule'] ];
		if ( ! $data['scheduled'] ) {
			$description = 'single' === $data['schedule'] ? __( 'Not scheduled', 'the-events-calendar' ) : $data['scheduleLabel'] . ' · ' . __( 'Not scheduled', 'the-events-calendar' );
		}
		$identity    = $data['isOccurrence'] ? __( 'Occurrence', 'the-events-calendar' ) : __( 'Event', 'the-events-calendar' );
		$description = $identity . ' · ' . $description;
		if ( $data['isOccurrence'] ) {
			$icon         = 'map-marker';
			$description .= '. ' . __( 'One scheduled date of this event', 'the-events-calendar' );
		}
		if ( $data['series'] ) {
			/* translators: %s: Names of Series containing the event. */
			$description .= '. ' . sprintf( __( 'Part of Series: %s', 'the-events-calendar' ), implode( ', ', wp_list_pluck( $data['series'], 'title' ) ) );
		}
		if ( $data['locked'] ) {
			$description .= '. ' . __( 'Recurrence editing locked.', 'the-events-calendar' ) . ' ' . $status['title'] . '. ' . $status['message'];
		}
		echo '<span class="tec-occurrence-admin__identity" data-description="' . esc_attr( $id . '-description' ) . '">';
		echo '<span class="screen-reader-text" id="' . esc_attr( $id . '-description' ) . '">' . esc_html( $description ) . '</span>';
		$this->indicator( $id . '-tooltip', $icon, $data['schedule'], $description, $data['locked'] );
		echo '</span>';
	}

	/**
	 * Renders a focusable information target and its associated, non-interactive tooltip.
	 *
	 * @since TBD
	 * @param string $id Unique tooltip ID.
	 * @param string $icon WordPress icon key.
	 * @param string $tone Visual schedule or membership family.
	 * @param string $description Plain-text accessible explanation.
	 * @param bool   $locked Whether recurrence editing is unavailable.
	 * @return void
	 */
	private function indicator( string $id, string $icon, string $tone, string $description, bool $locked ): void {
		echo '<span class="tec-occurrence-admin__indicator tec-occurrence-admin__indicator--' . esc_attr( $tone ) . ( $locked ? ' tec-occurrence-admin__indicator--locked' : '' ) . '">';
		echo '<button type="button" class="tec-occurrence-admin__trigger" data-icon="' . esc_attr( $icon ) . '" aria-label="' . esc_attr( $description ) . '" aria-describedby="' . esc_attr( $id ) . '">';
		echo '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="40" height="40" fill="currentColor" aria-hidden="true" focusable="false">';
		// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped, StellarWP.XSS.EscapeOutput.OutputNotEscaped -- Trusted static WordPress SVG paths, selected by an internal key.
		echo self::ICONS[ $icon ];
		echo '</svg></button>';
		echo '<span class="tec-occurrence-admin__tooltip" role="tooltip" id="' . esc_attr( $id ) . '">' . esc_html( $description ) . '</span>';
		echo '</span>';
	}
}
