<?php

namespace TEC\Events\Recurrence\Updates;

use Codeception\TestCase\WPTestCase;
use TEC\Events\Custom_Tables\V1\Models\Event;
use TEC\Events\Custom_Tables\V1\Models\Occurrence;
use TEC\Events\Custom_Tables\V1\Updates\Events as Events_Updates;
use TEC\Events\Recurrence\Authoring_Guard;
use TEC\Events\Recurrence\Date_Rules;
use TEC\Events\Recurrence\Dates;
use TEC\Events\Recurrence\Pro_History;
use TEC\Events\Recurrence\Settings;
use Tribe\Events\Test\Traits\With_Recurrence_Engine;
use WP_Error;
use WP_Post;

class Rules_ConversionTest extends WPTestCase {
	use With_Recurrence_Engine;

	/**
	 * The payloads captured from the before/after actions.
	 *
	 * @var array<string,array>
	 */
	public static array $actions = [];

	public static function capture_before( $post_id, $periods, $own_index ): void {
		self::$actions['before'] = [ (int) $post_id, count( $periods ), (int) $own_index ];
	}

	public static function capture_after( $post_id, $periods, $summary ): void {
		self::$actions['after'] = [ (int) $post_id, count( $periods ), $summary ];
	}

	/**
	 * Creates the Series relationships table Events Calendar Pro would: outside the per-test
	 * transaction, since DDL commits it.
	 */
	public static function wpSetUpBeforeClass(): void {
		global $wpdb;
		$table = Pro_History::series_relationships_table();
		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.SchemaChange
		$wpdb->query( "CREATE TABLE IF NOT EXISTS {$table} ( relationship_id bigint(20) unsigned NOT NULL AUTO_INCREMENT, series_post_id bigint(20) unsigned NOT NULL, event_id bigint(20) unsigned NOT NULL, event_post_id bigint(20) unsigned NOT NULL, PRIMARY KEY (relationship_id), KEY series_post_id (series_post_id), KEY event_post_id (event_post_id) )" );
	}

	public static function wpTearDownAfterClass(): void {
		global $wpdb;
		$table = Pro_History::series_relationships_table();
		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.SchemaChange
		$wpdb->query( "DROP TABLE IF EXISTS {$table}" );
		Pro_History::reset_table_check();
	}

	/**
	 * Makes sure the Series relationships table exists, as a REAL table.
	 *
	 * The test case rewrites CREATE TABLE into a temporary table `SHOW TABLES` does not
	 * list: the filters are lifted for the statement. Run first thing in the test, the
	 * implicit commit of the DDL has nothing of the test to commit.
	 */
	private function ensure_series_table(): void {
		global $wpdb;
		$table = Pro_History::series_relationships_table();

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
		if ( $wpdb->get_var( $wpdb->prepare( 'SHOW TABLES LIKE %s', $wpdb->esc_like( $table ) ) ) === $table ) {
			return;
		}

		remove_filter( 'query', [ $this, '_create_temporary_tables' ] );
		remove_filter( 'query', [ $this, '_drop_temporary_tables' ] );

		try {
			// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.SchemaChange
			$wpdb->query( "CREATE TABLE IF NOT EXISTS {$table} ( relationship_id bigint(20) unsigned NOT NULL AUTO_INCREMENT, series_post_id bigint(20) unsigned NOT NULL, event_id bigint(20) unsigned NOT NULL, event_post_id bigint(20) unsigned NOT NULL, PRIMARY KEY (relationship_id), KEY series_post_id (series_post_id), KEY event_post_id (event_post_id) )" );
		} finally {
			add_filter( 'query', [ $this, '_create_temporary_tables' ] );
			add_filter( 'query', [ $this, '_drop_temporary_tables' ] );
		}
	}

	/**
	 * @before
	 */
	public function unlock_and_capture(): void {
		$this->ensure_series_table();
		tribe_update_option( Settings::LOCK_OPTION, false );
		Pro_History::reset_table_check();
		self::$actions = [];
		add_action( 'tec_events_recurrence_before_rules_conversion', [ self::class, 'capture_before' ], 10, 3 );
		add_action( 'tec_events_recurrence_after_rules_conversion', [ self::class, 'capture_after' ], 10, 3 );
	}

	/**
	 * @after
	 */
	public function restore(): void {
		tribe_remove_option( Settings::LOCK_OPTION );
		// The per-test rollback runs before this: drop the settings cache so the next read reloads the restored DB.
		tribe_set_var( \Tribe__Settings_Manager::OPTION_CACHE_VAR_NAME, [] );
		remove_action( 'tec_events_recurrence_before_rules_conversion', [ self::class, 'capture_before' ], 10 );
		remove_action( 'tec_events_recurrence_after_rules_conversion', [ self::class, 'capture_after' ], 10 );
		remove_all_filters( 'tec_events_recurrence_conversion_max_dates' );
		remove_all_filters( 'tec_events_recurrence_conversion_trash_autogenerated_series' );
	}

	/**
	 * A rule-based Event on 2050-01-03 09:00 with rows on 2050-01-10 and 2050-01-17, its rules frozen.
	 */
	private function given_a_rule_locked_event( bool $with_meta = false ): WP_Post {
		$post = $this->given_a_multi_date_event(
			[
				[ 'start' => '2050-01-10 09:00:00', 'end' => '2050-01-10 10:00:00' ],
				[ 'start' => '2050-01-17 09:00:00', 'end' => '2050-01-17 10:00:00' ],
			],
			[
				'start_date' => '2050-01-03 09:00:00',
				'end_date'   => '2050-01-03 10:00:00',
				'timezone'   => 'America/Sao_Paulo',
			]
		);

		if ( $with_meta ) {
			// Written while the Event is still dates-only: the guard lets it through.
			update_post_meta(
				$post->ID,
				'_EventRecurrence',
				[
					'rules'       => [
						[
							'type'           => 'Weekly',
							'custom'         => [ 'interval' => 1 ],
							'end-type'       => 'After',
							'end-count'      => 3,
							'EventStartDate' => '2050-01-03 09:00:00',
							'EventEndDate'   => '2050-01-03 10:00:00',
						],
					],
					'exclusions'  => [],
					'description' => null,
				]
			);
			update_post_meta( $post->ID, '_tribe_blocks_recurrence_rules', '[{"type":"weekly"}]' );
		} else {
			delete_post_meta( $post->ID, '_EventRecurrence' );
		}

		Event::find( $post->ID, 'post_id' )->update(
			[ 'rset' => "DTSTART;TZID=America/Sao_Paulo:20500103T090000\nRRULE:FREQ=WEEKLY;COUNT=3;BYDAY=MO" ]
		);

		return $post;
	}

	/**
	 * @return array<string,array{occurrence_id: int, start_date: string, start_date_utc: string}> The rows keyed by start date.
	 */
	private function rows( int $post_id ): array {
		$rows = [];

		foreach ( Occurrence::where( 'post_id', '=', $post_id )->order_by( 'start_date', 'ASC' )->all() as $occurrence ) {
			$rows[ (string) $occurrence->start_date ] = [
				'occurrence_id'  => (int) $occurrence->occurrence_id,
				'start_date'     => (string) $occurrence->start_date,
				'start_date_utc' => (string) $occurrence->start_date_utc,
				'is_rdate'       => (bool) $occurrence->is_rdate,
			];
		}

		return $rows;
	}

	private function given_a_series( bool $autogenerated = true ): int {
		$series_id = wp_insert_post(
			[
				'post_type'   => Pro_History::SERIES_POST_TYPE,
				'post_status' => 'publish',
				'post_title'  => 'Test Series',
			]
		);
		$this->assertGreaterThan( 0, $series_id );

		if ( $autogenerated ) {
			update_post_meta( $series_id, Rules_Conversion::AUTOGENERATED_META_KEY, 1 );
		}

		return $series_id;
	}

	private function relate( int $series_id, int $post_id ): void {
		global $wpdb;
		$event = Event::find( $post_id, 'post_id' );
		$inserted = $wpdb->insert(
			Pro_History::series_relationships_table(),
			[
				'series_post_id' => $series_id,
				'event_id'       => (int) $event->event_id,
				'event_post_id'  => $post_id,
			],
			[ '%d', '%d', '%d' ]
		);
		$this->assertEquals( 1, $inserted, 'Relationship insert failed: ' . $wpdb->last_error );
	}

	private function relationships( int $post_id ): int {
		global $wpdb;
		$table = Pro_History::series_relationships_table();

		return (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$table} WHERE event_post_id = %d", $post_id ) );
	}

	/**
	 * It should refuse when the lock is enabled
	 *
	 * @test
	 */
	public function should_refuse_when_the_lock_is_enabled(): void {
		$post = $this->given_a_rule_locked_event();
		tribe_update_option( Settings::LOCK_OPTION, true );

		$result = tribe( Rules_Conversion::class )->convert( $post->ID );

		$this->assertInstanceOf( WP_Error::class, $result );
		$this->assertEquals( 'tec_events_recurrence_conversion_locked', $result->get_error_code() );
		$this->assertTrue( tribe( Authoring_Guard::class )->is_rule_locked( $post->ID ) );
		$this->assertEquals( [], self::$actions );
	}

	/**
	 * It should refuse a dates only event and a missing one
	 *
	 * @test
	 */
	public function should_refuse_a_dates_only_event_and_a_missing_one(): void {
		$post = $this->given_a_multi_date_event();

		$result = tribe( Rules_Conversion::class )->convert( $post->ID );
		$this->assertInstanceOf( WP_Error::class, $result );
		$this->assertEquals( 'tec_events_recurrence_not_rule_based', $result->get_error_code() );

		$result = tribe( Rules_Conversion::class )->convert( 999999 );
		$this->assertInstanceOf( WP_Error::class, $result );
		$this->assertEquals( 'tec_events_recurrence_event_not_found', $result->get_error_code() );
	}

	/**
	 * It should convert every occurrence into an explicit date keeping occurrence ids
	 *
	 * @test
	 */
	public function should_convert_every_occurrence_into_an_explicit_date_keeping_occurrence_ids(): void {
		$post   = $this->given_a_rule_locked_event( true );
		$before = $this->rows( $post->ID );
		$this->assertCount( 3, $before );

		$result = tribe( Rules_Conversion::class )->convert( $post->ID );

		$this->assertIsArray( $result, is_wp_error( $result ) ? $result->get_error_message() : '' );
		$this->assertEquals( 3, $result['count'] );
		$this->assertFalse( $result['start_moved'] );
		$this->assertEquals( 0, $result['detached'] );

		$after = $this->rows( $post->ID );
		$this->assertEquals( array_keys( $before ), array_keys( $after ), 'The same dates.' );
		foreach ( $before as $start => $row ) {
			$this->assertEquals( $row['occurrence_id'], $after[ $start ]['occurrence_id'], "The row on {$start} keeps its ID." );
			$this->assertEquals( $row['start_date_utc'], $after[ $start ]['start_date_utc'] );
			$this->assertTrue( $after[ $start ]['is_rdate'] );
		}

		$meta = get_post_meta( $post->ID, '_EventRecurrence', true );
		$this->assertTrue( Date_Rules::is_dates_only_meta( $meta ) );
		$this->assertCount( 2, $meta['rules'], 'The Event\'s own date is not an authored rule.' );
		$this->assertTrue( Dates::is_dates_only( Event::find( $post->ID, 'post_id' )->rset ) );
		$this->assertFalse( tribe( Authoring_Guard::class )->is_rule_locked( $post->ID ) );
		$this->assertCount( 2, tribe( Authoring_Guard::class )->get_authored_periods( $post->ID ) );
		$this->assertEmpty( get_post_meta( $post->ID, '_tribe_blocks_recurrence_rules', true ), 'The Pro blocks meta is gone.' );
		$this->assertEquals( '2050-01-03 09:00:00', get_post_meta( $post->ID, '_EventStartDate', true ) );

		$this->assertEquals( [ $post->ID, 3, 0 ], self::$actions['before'] );
		$this->assertEquals( $post->ID, self::$actions['after'][0] );
		$this->assertEquals( $result, self::$actions['after'][2] );

		// The dates are now editable through the service.
		$this->assertTrue( tribe( \TEC\Events\Recurrence\Dates_Service::class )->set_dates( $post->ID, [ [ 'start' => '2050-01-24 09:00:00', 'end' => '2050-01-24 10:00:00' ] ] ) );
		$this->assertCount( 2, $this->rows( $post->ID ) );
	}

	/**
	 * It should survive a later custom tables recommit
	 *
	 * @test
	 */
	public function should_survive_a_later_custom_tables_recommit(): void {
		$post = $this->given_a_rule_locked_event();

		$this->assertIsArray( tribe( Rules_Conversion::class )->convert( $post->ID ) );
		$after_conversion = $this->rows( $post->ID );

		// The meta-derived RSET must regenerate the very same rows.
		tribe( Events_Updates::class )->update( $post->ID );

		$this->assertEquals( $after_conversion, $this->rows( $post->ID ) );
	}

	/**
	 * It should collapse a single occurrence event to a plain event
	 *
	 * @test
	 */
	public function should_collapse_a_single_occurrence_event_to_a_plain_event(): void {
		$post = tribe_events()->set_args(
			[
				'title'      => 'Single Rule Event',
				'status'     => 'publish',
				'start_date' => '2050-01-03 09:00:00',
				'end_date'   => '2050-01-03 10:00:00',
				'timezone'   => 'UTC',
			]
		)->create();
		Event::find( $post->ID, 'post_id' )->update( [ 'rset' => "DTSTART;TZID=UTC:20500103T090000\nRRULE:FREQ=WEEKLY;COUNT=1" ] );
		$before = $this->rows( $post->ID );
		$this->assertCount( 1, $before );

		$result = tribe( Rules_Conversion::class )->convert( $post->ID );

		$this->assertIsArray( $result );
		$this->assertEquals( 1, $result['count'] );
		$this->assertEquals( $before, array_map( static fn( array $row ) => array_merge( $row, [ 'is_rdate' => false ] ), $this->rows( $post->ID ) ) );
		$this->assertEmpty( get_post_meta( $post->ID, '_EventRecurrence', true ) );
		$this->assertEquals( '', (string) Event::find( $post->ID, 'post_id' )->rset );
		$this->assertFalse( tribe( Authoring_Guard::class )->is_rule_locked( $post->ID ) );
	}

	/**
	 * It should use the earliest row when the own date is missing
	 *
	 * @test
	 */
	public function should_use_the_earliest_row_when_the_own_date_is_missing(): void {
		$post = $this->given_a_rule_locked_event();
		// Pro excluded the Event's own date: the row is gone, the Event still starts there.
		Occurrence::where( 'post_id', '=', $post->ID )->where( 'start_date', '=', '2050-01-03 09:00:00' )->delete();
		$this->assertCount( 2, $this->rows( $post->ID ) );

		$result = tribe( Rules_Conversion::class )->convert( $post->ID );

		$this->assertIsArray( $result );
		$this->assertTrue( $result['start_moved'] );
		$this->assertEquals( 2, $result['count'] );
		$this->assertEquals( '2050-01-10 09:00:00', get_post_meta( $post->ID, '_EventStartDate', true ) );
		$this->assertEquals( '2050-01-10 09:00:00', Event::find( $post->ID, 'post_id' )->start_date );
		$this->assertEquals( [ '2050-01-10 09:00:00', '2050-01-17 09:00:00' ], array_keys( $this->rows( $post->ID ) ) );
		$this->assertCount( 1, tribe( Authoring_Guard::class )->get_authored_periods( $post->ID ) );
	}

	/**
	 * It should refuse above the dates cap
	 *
	 * @test
	 */
	public function should_refuse_above_the_dates_cap(): void {
		$post = $this->given_a_rule_locked_event();
		add_filter( 'tec_events_recurrence_conversion_max_dates', static fn() => 2 );

		$result = tribe( Rules_Conversion::class )->convert( $post->ID );

		$this->assertInstanceOf( WP_Error::class, $result );
		$this->assertEquals( 'tec_events_recurrence_too_many_dates', $result->get_error_code() );
		$this->assertTrue( tribe( Authoring_Guard::class )->is_rule_locked( $post->ID ) );
	}

	/**
	 * It should detach the event from its series and trash an empty autogenerated series
	 *
	 * @test
	 */
	public function should_detach_the_event_from_its_series_and_trash_an_empty_autogenerated_series(): void {
		$post   = $this->given_a_rule_locked_event();
		$series = $this->given_a_series();
		$this->relate( $series, $post->ID );
		$this->assertEquals( 1, $this->relationships( $post->ID ) );

		$result = tribe( Rules_Conversion::class )->convert( $post->ID );

		$this->assertIsArray( $result );
		$this->assertEquals( 1, $result['detached'] );
		$this->assertEquals( 1, $result['trashed'] );
		$this->assertEquals( 0, $this->relationships( $post->ID ) );
		$this->assertEquals( 'trash', get_post_status( $series ) );
	}

	/**
	 * It should keep a series that still has events or is not autogenerated
	 *
	 * @test
	 */
	public function should_keep_a_series_that_still_has_events_or_is_not_autogenerated(): void {
		$post   = $this->given_a_rule_locked_event();
		$other  = $this->given_a_multi_date_event();
		$shared = $this->given_a_series();
		$manual = $this->given_a_series( false );
		$this->relate( $shared, $post->ID );
		$this->relate( $shared, $other->ID );
		$this->relate( $manual, $post->ID );

		$result = tribe( Rules_Conversion::class )->convert( $post->ID );

		$this->assertIsArray( $result );
		$this->assertEquals( 2, $result['detached'] );
		$this->assertEquals( 0, $result['trashed'] );
		$this->assertEquals( 0, $this->relationships( $post->ID ) );
		$this->assertEquals( 1, $this->relationships( $other->ID ) );
		$this->assertEquals( 'publish', get_post_status( $shared ) );
		$this->assertEquals( 'publish', get_post_status( $manual ) );
	}

	/**
	 * It should honor the trash filter
	 *
	 * @test
	 */
	public function should_honor_the_trash_filter(): void {
		$post   = $this->given_a_rule_locked_event();
		$series = $this->given_a_series();
		$this->relate( $series, $post->ID );
		add_filter( 'tec_events_recurrence_conversion_trash_autogenerated_series', '__return_false' );

		$result = tribe( Rules_Conversion::class )->convert( $post->ID );

		$this->assertEquals( 1, $result['detached'] );
		$this->assertEquals( 0, $result['trashed'] );
		$this->assertEquals( 'publish', get_post_status( $series ) );
	}
}
