<?php
/**
 * Converts a rule-based Event into an Event with individual dates.
 *
 * A rule-based Event (Events Calendar Pro recurrence rules, no rule engine active) keeps
 * its Occurrences frozen. Converting it turns every frozen Occurrence into an explicit,
 * authored date the free plugin manages: the rules are removed, no further date is ever
 * generated, and the Event leaves the Events Calendar Pro Series it belonged to. The
 * Occurrence rows are fed back as they are, so the regeneration matches them by date and
 * every Occurrence keeps its ID, its provisional post ID and its permalink.
 *
 * The conversion is irreversible: reactivating Events Calendar Pro reads the converted
 * Event as a list of dates, not as the rules it once had.
 *
 * @since TBD
 *
 * @package TEC\Events\Recurrence\Updates
 */

declare( strict_types=1 );

namespace TEC\Events\Recurrence\Updates;

use DateTimeImmutable;
use DateTimeZone;
use Exception;
use TEC\Events\Custom_Tables\V1\Models\Event;
use TEC\Events\Custom_Tables\V1\Models\Occurrence;
use TEC\Events\Custom_Tables\V1\Models\Provisional_Post;
use TEC\Events\Recurrence\Authoring_Guard;
use TEC\Events\Recurrence\Dates_Service;
use TEC\Events\Recurrence\Occurrences_List;
use TEC\Events\Recurrence\Pro_History;
use TEC\Events\Recurrence\Settings;
use WP_Error;
use WP_Post;

/**
 * Class Rules_Conversion.
 *
 * @since TBD
 *
 * @package TEC\Events\Recurrence\Updates
 */
class Rules_Conversion {
	/**
	 * The Block Editor recurrence meta keys Events Calendar Pro writes.
	 *
	 * @since TBD
	 *
	 * @var array<int,string>
	 */
	public const PRO_BLOCKS_META_KEYS = [
		'_tribe_blocks_recurrence_rules',
		'_tribe_blocks_recurrence_exclusions',
		'_tribe_blocks_recurrence_description',
	];

	/**
	 * The meta key flagging a Series Events Calendar Pro generated for a recurring Event.
	 *
	 * @since TBD
	 */
	public const AUTOGENERATED_META_KEY = '_tec_autogenerated';

	/**
	 * Converts a rule-based Event into an Event with individual dates.
	 *
	 * @since TBD
	 *
	 * @param int $post_id The Event post ID (a provisional ID is accepted).
	 *
	 * @return array{count: int, start_moved: bool, detached: int, trashed: int}|WP_Error The conversion summary
	 *                                                                                    (the number of dates, whether the
	 *                                                                                    Event's own date moved, the
	 *                                                                                    Series links removed and the Series
	 *                                                                                    trashed), or an error.
	 */
	public function convert( int $post_id ) {
		$post_id = Occurrence::normalize_id( $post_id );
		$event   = Event::find( $post_id, 'post_id' );

		if ( ! $event instanceof Event ) {
			return new WP_Error( 'tec_events_recurrence_event_not_found', __( 'The event could not be found.', 'the-events-calendar' ) );
		}

		if ( ! tribe( Authoring_Guard::class )->is_rule_locked( $post_id ) ) {
			return new WP_Error( 'tec_events_recurrence_not_rule_based', __( 'This event already uses individual dates.', 'the-events-calendar' ) );
		}

		if ( ! tribe( Settings::class )->can_convert( $post_id ) ) {
			return new WP_Error( 'tec_events_recurrence_conversion_locked', __( 'This event cannot be converted: the Events Calendar Pro recurrence lock is enabled.', 'the-events-calendar' ) );
		}

		$periods = $this->get_periods( $post_id );

		/**
		 * Filters the maximum number of dates a rule-based Event can be converted into.
		 *
		 * @since TBD
		 *
		 * @param int $max     The maximum number of dates; `0` removes the limit.
		 * @param int $post_id The Event post ID.
		 */
		$max = (int) apply_filters( 'tec_events_recurrence_conversion_max_dates', 1000, $post_id );

		if ( $max > 0 && count( $periods ) > $max ) {
			return new WP_Error(
				'tec_events_recurrence_too_many_dates',
				sprintf(
					/* translators: 1: the number of scheduled dates of the event. 2: the maximum number of dates that can be converted. */
					__( 'This event has %1$d scheduled dates, more than the %2$d dates that can be converted.', 'the-events-calendar' ),
					count( $periods ),
					$max
				)
			);
		}

		$own_index   = $this->find_own_period( $event, $periods );
		$start_moved = null === $own_index;

		if ( $start_moved ) {
			// The Event's own date is not among the rows: its first date follows the earliest one.
			$own_index = 0;
		}

		/**
		 * Fires before a rule-based Event is converted into an Event with individual dates.
		 *
		 * @since TBD
		 *
		 * @param int                                                                $post_id   The Event post ID.
		 * @param array<int,array{start: DateTimeImmutable, end: DateTimeImmutable}> $periods   The dates the Event will have, oldest first.
		 * @param int                                                                $own_index The index of the period becoming the Event's own date.
		 */
		do_action( 'tec_events_recurrence_before_rules_conversion', $post_id, $periods, $own_index );

		$written = tribe( Freeze_Guard::class )->allow(
			function () use ( $post_id, $periods, $own_index, $start_moved ): bool {
				if ( $start_moved ) {
					$this->write_event_dates( $post_id, $periods[ $own_index ]['start'], $periods[ $own_index ]['end'] );
					Event::upsert( [ 'post_id' ], Event::data_from_post( $post_id ) );
				}

				foreach ( self::PRO_BLOCKS_META_KEYS as $meta_key ) {
					// Left in place, Events Calendar Pro's Block Editor would read the rules back from them.
					delete_post_meta( $post_id, $meta_key );
				}

				$others = $periods;
				unset( $others[ $own_index ] );
				$others = array_values( $others );

				$service = tribe( Dates_Service::class );

				return count( $others ) ? $service->write_dates( $post_id, $others ) : $service->write_single( $post_id );
			}
		);

		if ( ! $written ) {
			return new WP_Error( 'tec_events_recurrence_conversion_failed', __( 'The event dates could not be written.', 'the-events-calendar' ) );
		}

		$series = $this->detach_series( $post_id );

		$this->flush_caches( $post_id );

		$summary = [
			'count'       => count( $periods ),
			'start_moved' => $start_moved,
			'detached'    => $series['detached'],
			'trashed'     => $series['trashed'],
		];

		/**
		 * Fires after a rule-based Event was converted into an Event with individual dates.
		 *
		 * @since TBD
		 *
		 * @param int                                                                $post_id The Event post ID.
		 * @param array<int,array{start: DateTimeImmutable, end: DateTimeImmutable}> $periods The dates the Event now has, oldest first.
		 * @param array{count: int, start_moved: bool, detached: int, trashed: int}  $summary The conversion summary.
		 */
		do_action( 'tec_events_recurrence_after_rules_conversion', $post_id, $periods, $summary );

		return $summary;
	}

	/**
	 * Returns the dates a rule-based Event would be converted into: its Occurrence rows.
	 *
	 * The rows are read in the Event timezone (the table stores Event-local wall-clock
	 * values) and floored to the minute, the precision the authored meta stores: meta and
	 * RSET must agree so a later re-derivation regenerates the same rows.
	 *
	 * @since TBD
	 *
	 * @param int $post_id The Event post ID (a provisional ID is accepted).
	 *
	 * @return array<int,array{start: DateTimeImmutable, end: DateTimeImmutable}> The dates, oldest first.
	 */
	public function get_periods( int $post_id ): array {
		$post_id = Occurrence::normalize_id( $post_id );
		$event   = Event::find( $post_id, 'post_id' );

		if ( ! $event instanceof Event ) {
			return [];
		}

		$timezone = tribe( Occurrences_List::class )->get_event_timezone( $post_id );
		$periods  = [];

		$occurrences = iterator_to_array(
			Occurrence::where( 'post_id', '=', $post_id )->order_by( 'start_date_utc', 'ASC' )->all(),
			false
		);

		foreach ( $occurrences as $occurrence ) {
			try {
				$start = $this->floor_to_minute( new DateTimeImmutable( (string) $occurrence->start_date, $timezone ) );
				$end   = $this->floor_to_minute( new DateTimeImmutable( (string) $occurrence->end_date, $timezone ) );
			} catch ( Exception $e ) {
				continue;
			}

			// Two rows on the same minute would author one date twice.
			$periods[ $start->format( 'U' ) ] = [
				'start' => $start,
				'end'   => $end,
			];
		}

		if ( ! count( $periods ) ) {
			// The freeze keeps the rows: an Event without any is an anomaly, recover as a single date.
			do_action( 'tribe_log', 'warning', 'Rule-based Event without Occurrence rows converted as a single date.', [ 'post_id' => $post_id ] );

			try {
				$periods[] = [
					'start' => $this->floor_to_minute( new DateTimeImmutable( (string) $event->start_date, $timezone ) ),
					'end'   => $this->floor_to_minute( new DateTimeImmutable( (string) $event->end_date, $timezone ) ),
				];
			} catch ( Exception $e ) {
				return [];
			}
		}

		return array_values( $periods );
	}

	/**
	 * Finds the period matching the Event's own date.
	 *
	 * @since TBD
	 *
	 * @param Event                                                              $event   The Event.
	 * @param array<int,array{start: DateTimeImmutable, end: DateTimeImmutable}> $periods The periods.
	 *
	 * @return int|null The index of the Event's own period, or `null` when none matches.
	 */
	private function find_own_period( Event $event, array $periods ): ?int {
		// The rows store the Event-local wall clock, as the Event does: compare to the minute, like the periods.
		$own_start = substr( (string) $event->start_date, 0, 16 );

		foreach ( $periods as $index => $period ) {
			if ( $period['start']->format( 'Y-m-d H:i' ) === $own_start ) {
				return $index;
			}
		}

		return null;
	}

	/**
	 * Writes the Event's own date meta, the way the Event API stores them.
	 *
	 * @since TBD
	 *
	 * @param int               $post_id The Event post ID.
	 * @param DateTimeImmutable $start   The new start, in the Event timezone.
	 * @param DateTimeImmutable $end     The new end, in the Event timezone.
	 *
	 * @return void
	 */
	private function write_event_dates( int $post_id, DateTimeImmutable $start, DateTimeImmutable $end ): void {
		$utc    = new DateTimeZone( 'UTC' );
		$format = 'Y-m-d H:i:s';

		update_post_meta( $post_id, '_EventStartDate', $start->format( $format ) );
		update_post_meta( $post_id, '_EventEndDate', $end->format( $format ) );
		update_post_meta( $post_id, '_EventStartDateUTC', $start->setTimezone( $utc )->format( $format ) );
		update_post_meta( $post_id, '_EventEndDateUTC', $end->setTimezone( $utc )->format( $format ) );
		update_post_meta( $post_id, '_EventDuration', (int) $end->format( 'U' ) - (int) $start->format( 'U' ) );
	}

	/**
	 * Removes the Event from its Events Calendar Pro Series.
	 *
	 * The relationships table is Pro's: nothing runs unless it exists. A Series Pro
	 * generated for the Event, left without any Event, is trashed like Pro does when
	 * the last Event of such a Series goes away.
	 *
	 * @since TBD
	 *
	 * @param int $post_id The Event post ID.
	 *
	 * @return array{detached: int, trashed: int} The relationship rows removed and the Series trashed.
	 */
	private function detach_series( int $post_id ): array {
		$result = [
			'detached' => 0,
			'trashed'  => 0,
		];

		if ( ! Pro_History::series_relationships_table_exists() ) {
			return $result;
		}

		global $wpdb;

		$table = Pro_History::series_relationships_table();

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.PreparedSQL.InterpolatedNotPrepared
		$series_ids = array_map( 'intval', (array) $wpdb->get_col( $wpdb->prepare( "SELECT DISTINCT series_post_id FROM {$table} WHERE event_post_id = %d", $post_id ) ) );

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
		$result['detached'] = (int) $wpdb->delete( $table, [ 'event_post_id' => $post_id ], [ '%d' ] );

		foreach ( $series_ids as $series_id ) {
			$series = get_post( $series_id );

			if (
				! $series instanceof WP_Post
				|| Pro_History::SERIES_POST_TYPE !== $series->post_type
				|| 'trash' === $series->post_status
				|| ! tribe_is_truthy( get_post_meta( $series_id, self::AUTOGENERATED_META_KEY, true ) )
			) {
				// A Series the user created stays; the Event is only unlinked from it.
				continue;
			}

			// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.PreparedSQL.InterpolatedNotPrepared
			$remaining = (int) $wpdb->get_var( $wpdb->prepare( "SELECT COUNT(*) FROM {$table} WHERE series_post_id = %d", $series_id ) );

			if ( $remaining > 0 ) {
				continue;
			}

			/**
			 * Filters whether an autogenerated Series left without Events by a conversion is trashed.
			 *
			 * @since TBD
			 *
			 * @param bool $trash     Whether to trash the Series.
			 * @param int  $series_id The Series post ID.
			 * @param int  $post_id   The converted Event post ID.
			 */
			if ( ! tribe_is_truthy( apply_filters( 'tec_events_recurrence_conversion_trash_autogenerated_series', true, $series_id, $post_id ) ) ) {
				continue;
			}

			if ( wp_trash_post( $series_id ) instanceof WP_Post ) {
				++$result['trashed'];
			}
		}

		return $result;
	}

	/**
	 * Flushes the caches carrying the Event's previous state.
	 *
	 * @since TBD
	 *
	 * @param int $post_id The Event post ID.
	 *
	 * @return void
	 */
	private function flush_caches( int $post_id ): void {
		tribe( Provisional_Post::class )->get_post_cache()->flush_occurrences( $post_id );
		wp_cache_delete( $post_id, 'tec_occurrence_matches' );
		clean_post_cache( $post_id );
	}

	/**
	 * Drops the seconds of a date.
	 *
	 * @since TBD
	 *
	 * @param DateTimeImmutable $date The date.
	 *
	 * @return DateTimeImmutable The date, on the minute.
	 */
	private function floor_to_minute( DateTimeImmutable $date ): DateTimeImmutable {
		return $date->setTime( (int) $date->format( 'G' ), (int) $date->format( 'i' ), 0 );
	}
}
