name: PHP Change Detector
on:
  workflow_call:
    inputs:
      skip-flag:
        description: 'Skip flag to check for (e.g., skip-phpcs)'
        required: false
        type: string
        default: ''
    outputs:
      has-php-changes:
        description: 'Whether PHP files have changed'
        value: ${{ jobs.conditional.outputs.has_php_changes }}
      should-run:
        description: 'Whether the workflow should run'
        value: ${{ jobs.conditional.outputs.should_run }}

jobs:
  conditional:
    if: ${{ inputs.skip-flag == '' || !contains(github.event.pull_request.body, format('[skip-{0}]', inputs.skip-flag)) }}
    runs-on: ubuntu-latest
    outputs:
      has_php_changes: ${{ steps.detect-changes.outputs.has_php_changes }}
      should_run: ${{ steps.detect-changes.outputs.should_run }}
    steps:
      # ------------------------------------------------------------------------------
      # Checkout the repo
      # ------------------------------------------------------------------------------
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          submodules: recursive

      # ------------------------------------------------------------------------------
      # Check if any PHP files have changed
      # ------------------------------------------------------------------------------
      - name: Check PHP file changes
        id: detect-changes
        run: |
          php_files=$(git diff ${{ github.event.pull_request.base.sha }} HEAD --name-only | grep -E '\.php$' || true)
          num_php_files=$(echo "$php_files" | grep -c '^' || echo 0)

          if [[ -z "$php_files" || "$num_php_files" -eq 0 ]]; then
            echo "has_php_changes=0" >> $GITHUB_OUTPUT
            echo "should_run=0" >> $GITHUB_OUTPUT
            echo "## No PHP files changed" >> $GITHUB_STEP_SUMMARY
            echo "Workflow will not run." >> $GITHUB_STEP_SUMMARY
          else
            echo "has_php_changes=1" >> $GITHUB_OUTPUT
            echo "should_run=1" >> $GITHUB_OUTPUT
            echo "## Found PHP file changes" >> $GITHUB_STEP_SUMMARY
            echo "Total changed PHP files: $num_php_files" >> $GITHUB_STEP_SUMMARY
            echo "$php_files" | sed 's/^/- /' >> $GITHUB_STEP_SUMMARY
          fi
