<?php
/**
 * Registers the Views v2 presentation of multi-Occurrence Events: the event object
 * decoration and the recurring markers.
 *
 * The whole provider yields when Events Calendar Pro is active: Pro decorates the event
 * object and renders its own (Series aware) markers.
 *
 * @since TBD
 *
 * @package TEC\Events\Recurrence
 */

declare( strict_types=1 );

namespace TEC\Events\Recurrence;

use TEC\Common\Contracts\Service_Provider;
use WP_Post;

/**
 * Class Views_Provider.
 *
 * @since TBD
 *
 * @package TEC\Events\Recurrence
 */
class Views_Provider extends Service_Provider {
	/**
	 * A map from the template inclusion actions to the recurring marker template each
	 * one should render after itself.
	 *
	 * @since TBD
	 */
	private const MARKERS = [
		'tribe_template_after_include:events/v2/day/event/date/meta'                                                      => 'day/event/recurring',
		'tribe_template_after_include:events/v2/list/event/date/meta'                                                     => 'list/event/recurring',
		'tribe_template_after_include:events/v2/month/calendar-body/day/calendar-events/calendar-event/date/meta'         => 'month/calendar-event/recurring',
		'tribe_template_after_include:events/v2/month/calendar-body/day/calendar-events/calendar-event/tooltip/date/meta' => 'month/calendar-event/tooltip/recurring',
		'tribe_template_after_include:events/v2/month/calendar-body/day/multiday-events/multiday-event/bar/title'         => 'month/calendar-event/multiday/recurring',
		'tribe_template_after_include:events/v2/month/mobile-events/mobile-day/mobile-event/date/meta'                    => 'month/mobile-event/recurring',
	];

	/**
	 * Registers the event decoration and the marker template injections.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	public function register() {
		$this->container->singleton( self::class, $this );

		if ( class_exists( 'Tribe__Events__Pro__Main', false ) ) {
			// Events Calendar Pro owns the event decoration and the markers.
			return;
		}

		if ( ! has_filter( 'tribe_get_event', [ $this, 'decorate_event' ] ) ) {
			add_filter( 'tribe_get_event', [ $this, 'decorate_event' ] );
		}

		foreach ( self::MARKERS as $action => $template ) {
			if ( ! has_action( $action, [ $this, 'render_recurring_marker' ] ) ) {
				add_action( $action, [ $this, 'render_recurring_marker' ], 10, 3 );
			}
		}
	}

	/**
	 * Unregisters the hooks added by the provider.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	public function unregister(): void {
		remove_filter( 'tribe_get_event', [ $this, 'decorate_event' ] );

		foreach ( array_keys( self::MARKERS ) as $action ) {
			remove_action( $action, [ $this, 'render_recurring_marker' ] );
		}
	}

	/**
	 * Decorates the event post object with the recurring flag and the all-Occurrences
	 * permalink.
	 *
	 * A previous decoration (e.g. Events Calendar Pro's) wins on the same properties.
	 *
	 * @since TBD
	 *
	 * @param WP_Post|mixed $post The decorated event post, as generated by the
	 *                            `tribe_get_event` function.
	 *
	 * @return WP_Post|mixed The decorated event post.
	 */
	public function decorate_event( $post ) {
		if ( ! $post instanceof WP_Post || isset( $post->recurring ) ) {
			return $post;
		}

		// The hydrated Occurrence carries the flag; fall back to the template tag.
		$recurring = isset( $post->_tec_occurrence->has_recurrence )
			? (bool) $post->_tec_occurrence->has_recurrence
			: tribe_is_recurring_event( $post->ID );

		$post->recurring = $recurring;

		if ( ! isset( $post->permalink_all ) ) {
			/*
			 * Until the all-Occurrences archive lands in this plugin the marker links to
			 * the Event permalink; Events Calendar Pro's decoration provides the `/all/`
			 * URL when active.
			 */
			$post->permalink_all = $recurring ?
				( function_exists( 'tribe_all_occurrences_link' )
					? tribe_all_occurrences_link( $post->ID, false )
					: get_permalink( $post->ID ) )
				: null;
		}

		return $post;
	}

	/**
	 * Renders the recurring marker template matching the template inclusion action that
	 * is firing.
	 *
	 * @since TBD
	 *
	 * @param string|mixed          $file     Complete path of the included PHP file.
	 * @param array<string>|mixed   $name     The template name fragments.
	 * @param \Tribe__Template|null $template The template instance being rendered.
	 *
	 * @return void
	 */
	public function render_recurring_marker( $file = null, $name = null, $template = null ): void {
		if ( ! $template instanceof \Tribe__Template ) {
			return;
		}

		$marker = self::MARKERS[ current_action() ] ?? null;

		if ( null === $marker ) {
			return;
		}

		$template->template( $marker, $template->get_values() );
	}
}
