<?php


interface Tribe__Events__REST__V1__Endpoints__Linked_Post_Endpoint_Interface
	extends Tribe__REST__Endpoints__READ_Endpoint_Interface,
	Tribe__REST__Endpoints__CREATE_Endpoint_Interface,
	Tribe__REST__Endpoints__DELETE_Endpoint_Interface {
}