name: Check changelog

on:
  pull_request:
    branches:
      - master
      - 'release/**'
    paths-ignore:
      - '.github/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check-changelog:
    name:    Check changelog
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.body, '[skip-changelog]')"
    steps:
      # Setup environment using action
      - name: Setup environment
        uses: the-events-calendar/actions/.github/actions/basic-setup@main
        with:
          setup-php: 'true'
          setup-node: 'false'
          php-version: '7.4'
          fetch-depth: '1000'

      # Enable composer caching
      - name: Get Composer Cache Directory
        id: composer-cache-dir
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # Install composer packages
      - name: Install composer dependencies
        run: composer self-update && composer install --no-progress --ignore-platform-reqs
      # Fetch the target branch before running the check.
      - name: Fetch the target origin branch
        run: git fetch origin $GITHUB_BASE_REF
      # Check if any changelog file is added when comparing the current branch vs the target branch.
      - name: Check changelog
        run: bash bin/check-changelog.sh origin/$GITHUB_BASE_REF HEAD
