name: Check changelog

on:
  pull_request:
    branches:
      - master
      - 'release/**'
    paths-ignore:
      - '.github/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check-changelog:
    name:    Check changelog
    runs-on: ubuntu-latest
    steps:
      - name: Check skip condition
        id: check-skip
        uses: the-events-calendar/actions/.github/actions/check-skip-flag@main
        with:
          skip-flag: changelog

      # Setup environment using action
      - name: Setup environment
        if: steps.check-skip.outputs.should-skip != 'true'
        uses: the-events-calendar/actions/.github/actions/base-setup@main
        with:
          setup-php: 'true'
          setup-node: 'false'
          php-version: '7.4'
          fetch-depth: '1000'

      # Setup composer with caching
      - name: Setup composer with caching
        if: steps.check-skip.outputs.should-skip != 'true'
        uses: the-events-calendar/actions/.github/actions/setup-composer@main

      # Fetch the target branch before running the check.
      - name: Fetch the target origin branch
        if: steps.check-skip.outputs.should-skip != 'true'
        run: git fetch origin $GITHUB_BASE_REF

      # Check if any changelog file is added when comparing the current branch vs the target branch.
      - name: Check changelog
        if: steps.check-skip.outputs.should-skip != 'true'
        run: bash bin/check-changelog.sh origin/$GITHUB_BASE_REF HEAD
