name: 'Link to Release Project'
on: [pull_request]
jobs:
  link-project:
    name: 'Link to Release Project'
    runs-on: ubuntu-latest
    steps:
      - uses: the-events-calendar/gh-action-project-link@main
        with:
          github-token: ${{ secrets.GHA_BOT_TOKEN_MANAGER }}
          template-project-url: https://github.com/orgs/the-events-calendar/projects/29
          project-owner: 'tec-bot'
          base-branch-pattern: 'release/*'
          name-prefix-remove: 'release/'
