name: 'npm lint'
on:
  pull_request:
  workflow_dispatch:
    paths:
      - 'src/modules/**.js'
      - 'src/resources/js/**.js'
      - 'src/resources/postcss/**.pcss'

jobs:
  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.body, '[skip-lint]')"
    steps:
      - name: Setup environment
        uses: the-events-calendar/actions/.github/actions/basic-setup@main
        with:
          setup-php: 'false'
          setup-node: 'true'

      # ------------------------------------------------------------------------------
      # Run linting tasks
      # ------------------------------------------------------------------------------
      - name: Run linting tasks
        run: npm run lint
