name: 'npm lint'
on:
  pull_request:
  workflow_dispatch:
    paths:
      - 'src/modules/**.js'
      - 'src/resources/js/**.js'
      - 'src/resources/postcss/**.pcss'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check skip condition
        id: check-skip
        uses: the-events-calendar/actions/.github/actions/check-skip-flag@main
        with:
          skip-flag: lint

      - name: Setup environment
        if: steps.check-skip.outputs.should-skip != 'true'
        uses: the-events-calendar/actions/.github/actions/base-setup@main
        with:
          setup-php: 'false'
          setup-node: 'true'

      # ------------------------------------------------------------------------------
      # Run linting tasks
      # ------------------------------------------------------------------------------
      - name: Install node modules
        if: steps.check-skip.outputs.should-skip != 'true'
        run: npm ci

      - name: Run linting tasks
        if: steps.check-skip.outputs.should-skip != 'true'
        run: npm run lint
