name: 'npm lint'
on:
  pull_request:
  workflow_dispatch:
    paths:
      - 'src/modules/**.js'
      - 'src/resources/js/**.js'
      - 'src/resources/postcss/**.pcss'

jobs:
  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.body, '[skip-lint]')"
    steps:
      # MODIFIED: Using reusable basic-setup workflow
      - name: Setup environment
        uses: ./.github/workflows/reusable/basic-setup.yml
        with:
          setup-php: false
          setup-node: true
          fetch-depth: 1

      # ------------------------------------------------------------------------------
      # Run linting tasks
      # ------------------------------------------------------------------------------
      - name: Run linting tasks
        run: npm run lint
