name: "Release: Process Changelogs"

# This action will run when it is triggered manually
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: "The release version for which the action should process the changelog (e.g. 4.5.0) (default: will try to figure it out)"
        default: 'figure-it-out'
        required: true
        type: string
      release-date:
        description: "The release date in human-readable format (default: 'today')."
        required: false
        default: "today"
        type: string
      action-type:
        description: "Whether this is to amend or generate the changelog entries (default: 'generate')."
        required: true
        default: "generate"
        type: choice
        options:
          - amend
          - generate
          - amend-version
      target-branch:
        description: "Target branch for the workflow"
        required: false
        type: string
        default: "main"
  workflow_call:
    inputs:
      release-version:
        description: "The release version for which the action should process the changelog (e.g. 4.5.0) (default: will try to figure it out)"
        default: 'figure-it-out'
        required: true
        type: string
      release-date:
        description: "The release date in human-readable format (default: 'today')."
        required: false
        default: "today"
        type: string
      action-type:
        description: "Whether this is to amend or generate the changelog entries (default: 'generate')."
        required: true
        default: "generate"
        type: string
      target-branch:
        description: "Target branch for the workflow"
        required: false
        type: string
        default: "main"

jobs:
  process-changelog:
    name: "Process the changelog"
    runs-on: ubuntu-latest
    outputs:
      changelog-content: ${{ steps.process-changelog.outputs.changelog-content }}
      changes-made: ${{ steps.process-changelog.outputs.changes-made }}
    steps:
      - name: Call reusable process-changelog workflow
        id: process-changelog
        uses: ./.github/workflows/reusable/release-process/process-changelog.yml
        with:
          release-version: ${{ inputs.release-version }}
          release-date: ${{ inputs.release-date }}
          action-type: ${{ inputs.action-type }}
          target-branch: ${{ inputs.target-branch || github.head_ref || github.ref_name }}

      # Create PR only when run individually
      - name: Create new branch
        id: versions
        if: github.event_name == 'workflow_dispatch'
        run: |
          changeBranch="task/process-changelog/${{ steps.format_date.outputs.RELEASE_DATE }}/${{ steps.figure_out_version.outputs.RELEASE_VERSION }}/${{ steps.vars.outputs.sha_short }}"
          git checkout -b "$changeBranch"
          git push origin "$changeBranch"

      - name: Create Pull Request
        if: github.event_name == 'workflow_dispatch'
        uses: peter-evans/create-pull-request@v6
        id: cpr
        with:
          token: ${{ secrets.GHA_BOT_TOKEN_MANAGER }}
          base: ${{ inputs.target-branch || github.ref }}
          branch: "task/process-changelog/${{ steps.format_date.outputs.RELEASE_DATE }}/${{ steps.figure_out_version.outputs.RELEASE_VERSION }}/${{ steps.vars.outputs.sha_short }}"
          title: "[BOT] Process changelog for '${{ inputs.target-branch || github.head_ref || github.ref_name }}'"
          body: |
            This is an automated PR created by ${{ github.actor }}.
            It was generated by [this GitHub Action](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
            [skip-changelog] *This PR was generated to move changelog files to the changelog list, thus it should not have a new changelog file.*
          labels: "automation"
          commit-message: |
            Process changelog for ${{ inputs.target-branch || github.ref }}
            This is an automated PR created by ${{ github.actor }}.
            Generated by: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Check outputs
        if: github.event_name == 'workflow_dispatch' && steps.cpr.outputs.pull-request-number
        run: |
          echo "## Pull Request"  >> $GITHUB_STEP_SUMMARY
          echo "* Number - ${{ steps.cpr.outputs.pull-request-number }}" >> $GITHUB_STEP_SUMMARY
          echo "* URL - [${{ steps.cpr.outputs.pull-request-url }}](${{ steps.cpr.outputs.pull-request-url }})" >> $GITHUB_STEP_SUMMARY
