name: "Release: Replace TBD Entries"
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Target branch"
        required: false
        type: string
        default: "main"

jobs:
  replace-tbd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set Variables
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
          echo "timestamp=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
          echo "current_branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Setup Git configuration
        uses: the-events-calendar/actions/.github/actions/setup-git@main

      - name: Create branch for changes
        id: create-branch
        run: |
          BRANCH_NAME="task/replace-tbd-${{ steps.vars.outputs.timestamp }}-${{ steps.vars.outputs.sha_short }}"
          git checkout -b "$BRANCH_NAME"
          # Push the branch immediately to establish it on remote
          git push --set-upstream origin "$BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Replace TBD entries
        id: replace-tbd
        uses: the-events-calendar/actions/.github/actions/replace-tbd-entries@main
        with:
          target-branch: ${{ inputs.branch }}

      - name: Commit changes
        if: steps.replace-tbd.outputs.changes-made == 'true'
        run: |
          git add -A
          git commit -m "Replace TBD entries with version ${{ steps.replace-tbd.outputs.current-version }}

          Automated replacement of TBD placeholders with current version.
          Generated by: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Push changes
        if: steps.replace-tbd.outputs.changes-made == 'true'
        run: |
          git push origin "${{ steps.create-branch.outputs.branch_name }}"

      - name: Create Pull Request
        if: steps.replace-tbd.outputs.changes-made == 'true'
        uses: peter-evans/create-pull-request@v7
        id: cpr
        with:
          token: ${{ secrets.GHA_BOT_TOKEN_MANAGER }}
          base: ${{ github.ref_name }}
          branch: ${{ steps.create-branch.outputs.branch_name }}
          title: "[BOT] Replace TBD entries with version ${{ steps.replace-tbd.outputs.current-version }}"
          body: |
            This is an automated PR created by ${{ github.actor }}.
            It was generated by [this GitHub Action](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).

            **Changes:**
            - Replaced TBD placeholders with version `${{ steps.replace-tbd.outputs.current-version }}`

            **Files modified:** See commit details for specific files changed.

            [skip-changelog] *This PR replaces TBD placeholders and doesn't require a changelog entry.*
          labels: "automation"
          assignees: ${{ github.actor }}
          reviewers: the-events-calendar/engineers

      - name: Display results
        run: |
          echo "## Results" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.replace-tbd.outputs.changes-made }}" == "true" ]; then
            echo "✅ TBD entries were found and replaced with version \`${{ steps.replace-tbd.outputs.current-version }}\`" >> $GITHUB_STEP_SUMMARY
            if [ "${{ steps.cpr.outputs.pull-request-number }}" ]; then
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "### Pull Request Created" >> $GITHUB_STEP_SUMMARY
              echo "- **Number**: [${{ steps.cpr.outputs.pull-request-number }}](${{ steps.cpr.outputs.pull-request-url }})" >> $GITHUB_STEP_SUMMARY
              echo "- **URL**: ${{ steps.cpr.outputs.pull-request-url }}" >> $GITHUB_STEP_SUMMARY
            fi
          else
            echo "ℹ️ No TBD entries found in the repository." >> $GITHUB_STEP_SUMMARY
          fi
