name: "Release: Process Changelog"

# This action will run when it is triggered manually
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: "The release version for which the action should process the changelog (e.g. 4.5.0) (default: will try to figure it out)"
        default: 'figure-it-out'
        required: true
        type: string
      release-date:
        description: "The release date in human-readable format (default: 'today')."
        required: false
        default: "today"
        type: string
      action-type:
        description: "Whether this is to amend or generate the changelog entries (default: 'generate')."
        required: true
        default: "generate"
        type: choice
        options:
          - amend
          - generate
          - amend-version
      changelog-full-url:
        description: "URL to link to the full changelog when trimming is applied (default: https://evnt.is/1b5k)."
        required: false
        default: "https://evnt.is/1b5k"
        type: string

defaults:
  run:
    shell: bash

jobs:
  process_changelog:
    name: "Process the changelog"
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: the-events-calendar/actions/.github/actions/base-setup@main
        with:
          setup-php: 'true'
          setup-node: 'false'
          php-version: '7.4'
          fetch-depth: '0'

      - name: Setup composer
        uses: the-events-calendar/actions/.github/actions/setup-composer@main

      - name: Set Variables
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Setup Git configuration
        uses: the-events-calendar/actions/.github/actions/setup-git@main

      - name: "Process changelog"
        id: process_changelog
        uses: the-events-calendar/actions/.github/actions/process-changelog@main
        with:
          release-version: ${{ github.event.inputs.release-version }}
          release-date: ${{ github.event.inputs.release-date }}
          action-type: ${{ github.event.inputs.action-type }}
          changelog-full-url: ${{ github.event.inputs.changelog-full-url }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        id: cpr
        with:
          token: ${{ secrets.GHA_BOT_TOKEN_MANAGER }}
          base: ${{ github.ref }}
          branch: "task/process-changelog/${{ github.event.inputs.release-date }}/${{ github.event.inputs.release-version }}/${{ steps.vars.outputs.sha_short }}"
          title: "[BOT] Process changelog for '${{ github.head_ref || github.ref_name }}'"
          body: |
            This is an automated PR created by ${{ github.actor }}.
            It was generated by [this GitHub Action](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
            [skip-changelog] *This PR was generated to move changelog files to the changelog list, thus it should not have a new changelog file.*
          labels: "automation"
          commit-message: |
            Process changelog for ${{ github.ref }}
            This is an automated PR created by ${{ github.actor }}.
            Generated by: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "## Pull Request"  >> $GITHUB_STEP_SUMMARY
          echo "* Number - ${{ steps.cpr.outputs.pull-request-number }}" >> $GITHUB_STEP_SUMMARY
          echo "* URL - [${{ steps.cpr.outputs.pull-request-url }}](${{ steps.cpr.outputs.pull-request-url }})" >> $GITHUB_STEP_SUMMARY

      - name: Display summary
        run: |
          echo "## Changelog Processing Complete" >> $GITHUB_STEP_SUMMARY
          echo "- **Release Version**: \`${{ github.event.inputs.release-version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Release Date**: \`${{ github.event.inputs.release-date }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Action Type**: \`${{ github.event.inputs.action-type }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "[skip-changelog] *This PR was generated to move changelog files to the changelog list, thus it should not have a new changelog file.*"
