name: "Release: Analyze Changes"

on:
  workflow_dispatch:
    inputs:
      compare-commit:
        description: "Commit to compare against (default: latest tag)"
        required: false
        type: string
        default: ""
      output-format:
        description: "Output format: changelog, list, or html"
        required: false
        type: choice
        options:
          - changelog
          - list
          - html
        default: "changelog"
      target-branch:
        description: "Target branch for the workflow"
        required: false
        type: string
        default: "main"
  workflow_call:
    inputs:
      compare-commit:
        description: "Commit to compare against (default: latest tag)"
        required: false
        type: string
        default: ""
      output-format:
        description: "Output format: changelog, list, or html"
        required: false
        type: string
        default: "changelog"
      target-branch:
        description: "Target branch for the workflow"
        required: false
        type: string
        default: "main"

jobs:
  analyze-changes:
    name: "Analyze Changes"
    runs-on: ubuntu-latest
    outputs:
      analysis-summary: ${{ steps.analyze-changes.outputs.analysis-summary }}
      changes-detected: ${{ steps.analyze-changes.outputs.changes-detected }}
    steps:
      - name: Analyze changes
        id: analyze-changes
        uses: the-events-calendar/actions/.github/actions/analyze-changes@main
        with:
          compare-commit: ${{ inputs.compare-commit }}
          output-format: ${{ inputs.output-format }}

      # Create PR only when run individually
      - name: Create Pull Request
        if: github.event_name == 'workflow_dispatch' && steps.analyze-changes.outputs.changes-detected == 'true'
        uses: peter-evans/create-pull-request@v7
        id: create-pr
        with:
          token: ${{ secrets.GHA_BOT_TOKEN_MANAGER }}
          base: ${{ inputs.target-branch || github.head_ref || github.ref_name }}
          branch: "task/analyze-changes-$(date +%Y%m%d-%H%M%S)-$(git rev-parse --short ${{ github.sha }})"
          title: "[BOT] Analyze changes for '${{ inputs.target-branch || github.head_ref || github.ref_name }}'"
          body: |
            ## Change Analysis Results

            This PR contains the analysis of changes detected in the codebase.

            ${{ steps.analyze-changes.outputs.analysis-summary }}

            ---
            *This PR was automatically generated by the change analysis workflow.*
          labels: "automation,analysis"
          assignees: ${{ github.actor }}
          reviewers: the-events-calendar/engineers
          commit-message: |
            Analyze changes for ${{ inputs.target-branch || github.head_ref || github.ref_name }}

            This is an automated PR created by ${{ github.actor }}.
            Generated by: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Check outputs
        if: github.event_name == 'workflow_dispatch' && steps.analyze-changes.outputs.changes-detected == 'true' && steps.create-pr.outputs.pull-request-number
        run: |
          echo "## Pull Request" >> $GITHUB_STEP_SUMMARY
          echo "* Number - ${{ steps.create-pr.outputs.pull-request-number }}" >> $GITHUB_STEP_SUMMARY
          echo "* URL - [${{ steps.create-pr.outputs.pull-request-url }}](${{ steps.create-pr.outputs.pull-request-url }})" >> $GITHUB_STEP_SUMMARY

      - name: No changes
        if: github.event_name == 'workflow_dispatch' && steps.analyze-changes.outputs.changes-detected == 'false'
        run: |
          echo "## No Pull Request Created" >> $GITHUB_STEP_SUMMARY
          echo "No changes were detected in the analysis." >> $GITHUB_STEP_SUMMARY
