name: "Release: Replace TBD Entries"

on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: "Target branch for the workflow"
        required: false
        type: string
        default: "main"
  workflow_call:
    inputs:
      target-branch:
        description: "Target branch for the workflow"
        required: false
        type: string
        default: "main"
    secrets:
      GHA_BOT_TOKEN_MANAGER:
        required: true

jobs:
  replace-tbd:
    runs-on: ubuntu-latest
    outputs:
      changes-made: ${{ steps.replace-tbd.outputs.changes-made }}
      current-version: "The current version found"
        value: ${{ steps.replace-tbd.outputs.current-version }}
    steps:
      - name: Call reusable replace-tbd-entries workflow
        id: replace-tbd
        uses: ./.github/workflows/reusable/release-process/replace-tbd-entries.yml
        with:
          target-branch: ${{ inputs.target-branch || github.head_ref || github.ref_name }}

      # Create PR only when run individually
      - name: Create branch for changes
        id: create-branch
        if: github.event_name == 'workflow_dispatch' && steps.replace-tbd.outputs.changes-made == 'true'
        run: |
          timestamp=$(date +%Y%m%d-%H%M%S)
          sha_short=$(git rev-parse --short ${{ github.sha }})
          BRANCH_NAME="task/replace-tbd-$timestamp-$sha_short"
          git checkout -b "$BRANCH_NAME"
          # Push the branch immediately to establish it on remote
          git push --set-upstream origin "$BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: github.event_name == 'workflow_dispatch' && steps.replace-tbd.outputs.changes-made == 'true'
        uses: peter-evans/create-pull-request@v6
        id: cpr
        with:
          token: ${{ secrets.GHA_BOT_TOKEN_MANAGER }}
          base: "${{ inputs.target-branch || github.ref_name }}"
          branch: "${{ steps.create-branch.outputs.branch_name }}"
          title: "[BOT] Replace TBD entries with version ${{ steps.replace-tbd.outputs.current-version }}"
          body: |
            This is an automated PR created by ${{ github.actor }}.
            It replaces all "TBD" entries in the codebase with the current version: ${{ steps.replace-tbd.outputs.current-version }}

            Generated by: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          labels: "automation"
          commit-message: |
            Replace TBD entries with version ${{ steps.replace-tbd.outputs.current-version }}

            This is an automated PR created by ${{ github.actor }}.
            Generated by: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          delete-branch: false
          push-to-fork: ''

      - name: Check outputs
        if: github.event_name == 'workflow_dispatch' && steps.replace-tbd.outputs.changes-made == 'true' && steps.cpr.outputs.pull-request-number
        run: |
          echo "## Pull Request" >> $GITHUB_STEP_SUMMARY
          echo "* Number - ${{ steps.cpr.outputs.pull-request-number }}" >> $GITHUB_STEP_SUMMARY
          echo "* URL - [${{ steps.cpr.outputs.pull-request-url }}](${{ steps.cpr.outputs.pull-request-url }})" >> $GITHUB_STEP_SUMMARY

      - name: No changes
        if: github.event_name == 'workflow_dispatch' && steps.replace-tbd.outputs.changes-made == 'false'
        run: |
          echo "## No Pull Request Created" >> $GITHUB_STEP_SUMMARY
          echo "No TBD entries were found or changed in the repository." >> $GITHUB_STEP_SUMMARY
